#!/bin/bash
 
log=installed_files
if [ -f $log ] ; then
    cat $log | xargs rm -rf
    rm -f $log
    echo "The software has been uninstalled"
fi

if [ -f "/usr/local/share/applications/kugou.desktop" ] ; then
	rm -rf /usr/local/share/applications/kugou.desktop
fi

if [ -f "/usr/local/share/icons/kugou.png" ] ; then
	rm -f /usr/local/share/icons/kugou.png
fi
