#!/usr/bin/python
  
# Copyright (C) 2012 mutse <yyhoo2.young@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import gtk
import webkit
import sys

class WebKugou(gtk.Window):
    def __init__(self):
        super(WebKugou,self).__init__()
        
        view = webkit.WebView()
        vbox = gtk.VBox(spacing=1) 
        vbox.pack_start(view)
        self.add(vbox)

        self.set_default_size(700, 518)
        self.set_title('Kugou Music')
        self.set_position(gtk.WIN_POS_CENTER)
        self.tray = gtk.StatusIcon()
        self.tray.set_from_file("/usr/local/share/icons/kugou.png")
        self.tray.connect('popup-menu', self.on_right_click)

        try:
            self.set_icon_from_file("/usr/local/share/icons/kugou.png")
        except Exception, e:
            print e.message
            sys.exit(1)

        self.connect('destroy', gtk.main_quit)
        self.show_all()

        view.open("http://web.kugou.com")

    def on_right_click(self, icon, event_button, event_time):
        menu = gtk.Menu()

        about = gtk.MenuItem('About')
        about.show()
        menu.append(about)
        about.connect('activate', self.show_about_dialog)

        quit = gtk.MenuItem('Quit')
        quit.show()
        menu.append(quit)
        quit.connect('activate', gtk.main_quit)

        menu.popup(None, None, gtk.status_icon_position_menu, event_button, event_time, self.tray)

    def show_about_dialog(self, widget):
        about_dialog = gtk.AboutDialog()
        about_dialog.set_destroy_with_parent(True)
        about_dialog.set_name('Kugou Music')
        about_dialog.set_version('1.0.1')
        about_dialog.set_comments((u'This is a online player of Kugou Music'))
        about_dialog.set_authors([u'Mutse Young <yyhoo2.young@gmail.com>'])
        about_dialog.run()
        about_dialog.destroy()

if __name__ == "__main__":
    WebKugou()
    gtk.main()

